<?php

/**
 * @var Model_User $user
 */
$user = $view->getParam('user');
?>

<?php if ($user) : ?>
    <table border="2px">
        <th>Id</th>
        <th>Name</th>
        <th>Email</th>
        <tr>
            <td><?php echo $user->id; ?></td>
            <td><?php echo $user->name; ?></td>
            <td><?php echo $user->email; ?></td>
        </tr>
    </table>

<?php elseif ($view->getParam('error')) : ?>
    <div class = 'error'><?php echo $view->getParam('error') ?></div>
<?php endif; ?>