<html>
    <head>
        <title>Project</title>
        <link rel="stylesheet" type="text/css" href="/css/style.css" />
        <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>        
        <!--<script type="text/javascript" src="/js/jquery.js"></script>-->
        <script type="text/javascript" src="/js/authorize.js?333"></script>
       
        
    </head>    
    <body>  
        <div id="error"><?php //echo !empty($errorMessage) ? $errorMessage : ''; ?></div>

        <div id="userEmail"><?php //echo !empty($userId) ? 'Вы зашли как: ' : '';?><!--<a href="<?php //echo !empty($userId)? '/user/profile/id/'.$userId : '';?>"><?php //echo !empty($userEmail) ? $userEmail : ''; ?></a>--></div>
        <div id="userId"><a id="logout" href="#"><?php echo !empty($userId) ? 'Exit' : ''?></a></div>

        <div id="loginFormDiv" <?php if(!empty($userEmail)) { echo 'class = "hide"'; } ?> >
            <form name="authorize" id="loginForm" method="POST" autocomplete="off">
                <input placeholder="Email" type="text" name="email" maxlength="20" /><br />
                <input placeholder="Password" type="password" name="password" maxlength="30" /><br />
                <input id="save_checkbox" type="checkbox" name="save" value="1" /><label for="save_checkbox">Save</label><br />
                <input type="submit" name="login" value="Enter" />
                <input type="submit" name="register" value="Register" />
            </form>
        </div>
           <div id="menu">
                <a href="/">Главная </a> &nbsp&nbsp | &nbsp&nbsp
                <a href="/product/index">Продукты </a>  &nbsp&nbsp | &nbsp&nbsp
                <a href="/company/portfolio">Портфолио </a>  &nbsp&nbsp | &nbsp&nbsp
                <a href="/company/about">О компании </a>  &nbsp&nbsp | &nbsp&nbsp
                <a href="/company/contact">Контакты </a>  &nbsp&nbsp | &nbsp&nbsp
                <?php //if ($userRoleId == Model_User::ROLE_ADMIN_ID) : ?>
                    <a id="admin_href" href="/admin/index" style="<?php //if($userRoleId != Model_User::ROLE_ADMIN_ID) { echo 'display: none;'; } ?>">Админка </a>  &nbsp&nbsp
                <?php //endif; ?>
            </div>
        <br />
        <hr />

    <?php
        
   
    if(file_exists($viewFileName)) {
        include $viewFileName;
    }
    ?>
        
    <hr />    
    <div>Здесь может быть ваша реклама</div>    
    
    </body>
    
</html>